build:
  system_packages:
    - "ffmpeg"
    - "libtesseract-dev"
  python_packages:
    - "torch==2.0.1"
    - "torchsde"
    - "einops"
    - "transformers>=4.25.1"
    - "safetensors>=0.3.0"
    - "aiohttp"
    - "accelerate"
    - "pyyaml"
    - "Pillow"
    - "scipy"
    - "tqdm"
    - "psutil"
    - "requests"
    - "torchvision"
    - "uuid"
    - "onnxruntime"
    - "opencv-python"
    - "get-port"
    # efficiency-nodes-comfyui
    - "clip-interrogator"
    - "simpleeval"
    # hd-nodes-comfyui
    - "insightface"
