build:
  system_packages:
    - "ffmpeg"
    - "libtesseract-dev"
    - "libgl1-mesa-glx"
    - "libglib2.0-0"
  python_packages:
    - "torch==2.0.1"
    - "torchsde"
    - "einops"
    - "transformers>=4.25.1"
    - "safetensors>=0.3.0"
    - "aiohttp"
    - "accelerate"
    - "pyyaml"
    - "Pillow"
    - "scipy"
    - "tqdm"
    - "psutil"
    - "requests"
    - "torchvision"
    - "uuid"
    - "onnxruntime"
    - "opencv-python"
    - "get-port"
    # efficiency-nodes-comfyui
    - "clip-interrogator"
    - "simpleeval"
    # hd-nodes-comfyui
    - "insightface"
    - "openmim"
    - "segment-anything"
    - "ultralytics"
    - "scikit-image"
    - "piexif"
    - "pycocotools"
    - "onnxruntime-gpu"
    # was-node-suite-comfyui
    - "cmake"
    - "fairscale>=0.4.4"
    - "git+https://github.com/WASasquatch/img2texture.git"
    - "git+https://github.com/WASasquatch/cstr"
    - "gitpython"
    - "imageio"
    - "joblib"
    - "matplotlib"
    - "numba"
    - "numpy>=1.18.5, <1.25.0"
    - "opencv-python-headless[ffmpeg]<=4.7.0.72"
    - "pilgram"
    - "git+https://github.com/WASasquatch/ffmpy.git"
    - "rembg"
    - "scikit-image==0.20.0"
    - "scikit-learn"
    - "timm>=0.4.12"
    - "transformers==4.26.1"
