build:
  system_packages:
    - "ffmpeg"
    - "libtesseract-dev"
    - "opencv-python"
    - "numba"
    - "numexpr"
    - "inference_core_nodes"
    - "kornia"
    - "onnxruntime"
  python_packages:
    - "torch"
    - "torchsde"
    - "einops"
    - "transformers>=4.25.1"
    - "safetensors>=0.3.0"
    - "aiohttp"
    - "accelerate"
    - "pyyaml"
    - "Pillow"
    - "scipy"
    - "tqdm"
    - "psutil"
    - "requests"
    - "torchvision"
    - "opencv-python"
    - "numba"
    - "numexpr"
    - "inference_core_nodes"
    - "kornia"
    - "onnxruntime"
    - "websocket"
